### ISSUE TITLE
Set up GA4

### ISSUE THREAD

**Issue by jonohey** [jonohey/sketchplanations#184]
https://analytics.google.com/analytics/web/?hl=en-GB&pli=1#/a41793508w71338295p73590241/admin/ga4-setup-assistant

```
<!-- Google tag (gtag.js) -->
<script async src="https://www.googletagmanager.com/gtag/js?id=G-0FBCPE6ME4"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-0FBCPE6ME4');
</script>
```

![Image](https://user-images.githubusercontent.com/1498914/217646719-dba37851-a8b0-48c2-9154-48ce3b7541f1.png)

Or perhaps just easiest to install Google Tag Manager and manage it and Hotjar etc from there

From their email:

We’ll soon configure Google Analytics 4 for you

Hello.

Universal Analytics standard properties will stop processing data on 1 July 2023. To maximise historical data and to ensure that Google Analytics 4 (GA4) meets your specific needs, [we recommend you make the switch to Google Analytics 4 now](https://notifications.google.com/g/p/APdRdFxW1pNfHtVN6fLgZBipZREOwB1kX3bPZQ0ar1s6U1Esme7u39kc0Ao_tI2-J3reMadLWb9b6ZuuIHYqPI-22r4uMRYsZEl-VBGsHz4I_NEaDTnxFcVUHQrHXuFz8Gj_xPhDaXwfUrv_uhPoRpVZxIBQkQAx46Y8Z0lmSSFnlEYrxEAGdNmjGy58yolz94mzxoqDp7nucgzZHCOmb-c1pkSYVAGiys6Y8T51t-Zr89loNKuXHBDijpHa5YJlFiOEfGvs8X42MyHqpNoz9RbMbLBt0YzrruJ8LDqiyvpY3Nkfe4pk57lFzoG17so8Pj99V5b6rFHdO8O8vySePSOpZxmrUQ). This will give you the opportunity to customise the setup including using the latest site tag.

For any customer who does not set up a GA4 property with basic settings, starting in March, we will configure one with a few basic settings consistent with the existing Universal Analytics property; this includes certain conversion events, Google Ads links and existing website tags. Enhanced Measurement will be configured to match only some of your Universal Analytics settings; review these settings to ensure that they match your needs.

For Universal Analytics customers whose websites are tagged with gtag.js or analytics.js (including through tag management systems like Google Tag Manager), we will create a connected site tag that will reuse existing tags when possible to send traffic to the new GA4 property. If you do not wish to have a GA4 property created and configured based on your Universal Analytics property and existing tags, [you may opt out](https://notifications.google.com/g/p/APdRdFx4TZEgbAitfeooK0eVU6of30eIll6H_FFC2MCannqdL5C-8gNpfHIuSqZ6iTN_71Rd1GPtFZc56f9XakzEZqgrTzklTE8JPBNzhXbuL59o6nSs6XGYopFNoRrEUFyrJZ3jcKWAA79Cqcpiu3Kl9NfWr8lIGYpXgw_wML4qk7tz7gIQ6Ea4Zcgy0Sd83ZChnP__Yx_a4y0sUoqhxtP4XytbE4HH18pVtIKQd9QknG3ttwvrgbdAl9b6fVuoqnbGqEo3eXo2CLGYE_MENZ4fZboedemGrJGBN2dqtOLkt_RDuHDoNUc-qYCL).

[Learn more](https://notifications.google.com/g/p/APdRdFzOtuvYGJflO4IYteQE1kJTaRGHq1TVtAz2qQDAzMKIZTWBeHwwjTSsIFFXHgBWiU2sb2ofEdhN8k1v4XmPMSDGqkJiQzIRGtLzl7OLi9sewe3NFnITz44TNuHe9k41MgcY6s9Ac6XrBj4wsZ6r6exsUnMd1yRHQO18L1S_eBPfI-KCY-ApgFjyAyQg4dvoPXd-_fVR61db6bn00xuMypzJZCB3MNCESoP3bPN9Z6YOXL_SdnZWBhUuqigKIjm8esaQc6aM4F_4QoWuGKHNMNBRv1bDOEN4s5rgSn4vbdBB9AsxemQ)

**Comment by alistairholt** [comment]
It turns out that we did implement it via GTM. I've set up GA4 in GTM and published the changes. I paused the old  **Google Analytics Universal Analytics** tag.
