### ISSUE TITLE
Reorder tabs according to suggestion

### ISSUE THREAD

**Issue by jonohey** [jonohey/sketchplanations#194]

**Comment by alistairholt** [comment]
> I think there are some improvements to the nav still to make. It’s weird not to be able to find the about page at all on mobile, and with Tags so prominent it feels like it could be stronger, should start on the frequency, which should probably have higher contrast, and maybe the tags should be bigger on mobile too.

**Comment by alistairholt** [comment]
- [ ] Reinstate `About` nav item on small screens
- [ ] Make `Frequency` the default sort option on the tags page
- [ ] Fix the weird look of the sort options when in light mode

![Image](https://user-images.githubusercontent.com/5109/232247357-150b8fe1-e1f5-444e-a65b-447a4edefa8f.png)
