### ISSUE TITLE
Fix mobile usability issues from Google Search console (items too close together?)

### ISSUE THREAD

**Issue by jonohey** [jonohey/sketchplanations#207]
https://search.google.com/search-console/mobile-usability?resource_id=sc-domain:sketchplanations.com&utm_source=wnc_10030322&utm_medium=gamma&utm_campaign=wnc_10030322&utm_content=msg_100058679&hl=en-GB

![Image](https://user-images.githubusercontent.com/1498914/229356653-6b2d6c67-5b77-446a-8aad-4d0b871854cc.png)

![Image](https://user-images.githubusercontent.com/1498914/229356684-359c8304-4fb1-4564-9d85-f6b0da95670d.png)

**Comment by alistairholt** [comment]
Closed by f91881b
