### ISSUE TITLE
Spike: Review Bing SEO Report errors and plan tickets to address

### ISSUE THREAD

**Issue by jonohey** [jonohey/sketchplanations#208]
Bing's SEO Report tool reports a stack of errors. Also, I know that we, in the past, submitted URLs to bing. I wonder if we need to do that again?

https://www.bing.com/webmasters/seoreports?tid=41c14c4c-171c-4000-8823-cc68c10e5a77

![Image](https://user-images.githubusercontent.com/1498914/229356828-9a5c63cd-949d-44d0-8364-4f46ef22cd4a.png)

**Comment by alistairholt** [comment]
I've addressed all of these in the following commits:

- f5e8c90c03c11c787605a50393b45b58c6b95d70
- 4b15a15ac720f03de6910776ddcda22e2ecb15e3
- 723cecd44eccb0231ef0d15c32444ef330c0ab10
- b4b9c523d53b63ab209b17538016a9e86de5a9b9
