### ISSUE TITLE
Add About info to homepage

### ISSUE THREAD

**Issue by jonohey** [jonohey/sketchplanations#460]
Basic information

On left:

I'm Jono 👋 

I'm a designer and illustrator creating one of the world's largest libraries of hand-drawn sketches explaining big ideas—sketch-by-sketch.

Sketchplanations have been shared millions of times and used in a host of books and articles. Learn more about the project or find a sketch you like

On right:
Explore sketches for:
- Teachers
- Managers
- Developers
- Product managers
- Productivity
- Thinkers
- Loads more

**Comment by lkilu6456546** [comment]
Hello, I tried to solve the issue.

This is what I did:

Added new sections to the home page including an introduction and exploration links. Maintained existing styling and structure while incorporating the new content.

You can review changes in this commit: https://github.com/lkilu6456546/jonohey-sketchplanations-460/commit/f3162484c36d5e8ac37f0db51a68fff07c198f29.


> [!CAUTION]
> Disclaimer: The concept of solution was created by AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---

If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.
