### ISSUE TITLE
Serve RSS feed as xml file instead of "application/octet-stream"

### ISSUE THREAD

**Issue by binyamin** [jonohey/sketchplanations#64]
The content-type of the rss feed is currently "application/octet-stream". You can verify this with `curl -I https://sketchplanations.com/rss` This means that some feed readers will, like mine, have trouble processing the feed. Because it has an `xmlns:atom` attribute, I assume the feed is technically an atom feed. So, you would want to serve it as `application/atom+xml` (or `application/xml` if you want).

**Comment by binyamin** [comment]
This seems to be a problem with Vercel, because there's a different "Content-Type" set in `/vercel.json`.

**Comment by jonohey** [comment]
Thanks, Binyamin. Very odd!

**Comment by binyamin** [comment]
Apparently it works when you set the headers in next.config.js :shrug:

**Comment by alistairholt** [comment]
> Apparently it works when you set the headers in next.config.js :shrug:

Thank you for looking into it! We recently came to the same conclusion on another issue that came to light recently. I'm still not sure if it was Vercel change or a Next change but moving the config to `next.config.js` was the solution there too.

**Comment by alistairholt** [comment]
Fixed in 6895816f. Thanks again @binyamin!
